### ISSUE TITLE
[Bug]: OVH provider returns 401 error

### ISSUE THREAD

**Issue by xakraz** [govirtuo/cfcr#9]
### Version

v3.0.0 (built: 2023-05-25_12:14:02TUTC)

### What happened?

Cfcr logs report a 401 error while trying to access OVH API and then panic

### Relevant log output

![image](https://github.com/govirtuo/cfcr/assets/1590399/6ed3d459-a179-40d8-80d1-c8981987a6dc)

```bash
```

**Comment by eze-kiel** [comment]
Hi, thanks for reporting this issue. After having a quick look, I think the line responsible of the `panic` is the following:

https://github.com/govirtuo/cfcr/blob/daafd89ffeb9b22cf6592078a460527468a16b51/cloudflare/cloudflare.go#L68

However, the following lines should prevent this from happening:

https://github.com/govirtuo/cfcr/blob/daafd89ffeb9b22cf6592078a460527468a16b51/cloudflare/cloudflare.go#L64-L66

Maybe we should add another check, something like (pseudo code):

```
if len(holder.Result) != 1; then
  return error
fi
```

to avoid accessing a non-existent array index.

About the 401 error, are you sure the OVH credentials are still valid? As far as I remember they should be, but we never know :innocent: 

Maybe you should try to do a request with cURL using them to try to access the OVH API. Please note that the credentials (should) have a well-defined scope (as defined in the doc [here](https://github.com/govirtuo/cfcr/tree/main#ovh)) so you must try on a valid route.

Another possibility is that the API has changed, and maybe the routes are no longer valid. At the time of writing this program, there was no good package that wrapped the OVH API, so the routes have been hard-coded in the `ovh.go` file ([example](https://github.com/govirtuo/cfcr/blob/daafd89ffeb9b22cf6592078a460527468a16b51/providers/ovh/ovh.go#L40)). They may need to be updated in case of a change on their side.

GLHF, and keep me posted :wink:

**Comment by xakraz** [comment]
Hi @eze-kiel 👋🏻 

Thanks for answering this issue 🙏🏻  

I have done some investigations regarding the OVH credentials.
* ✅ The OVH `app_key` in our running configuration is associated to an "active" application on OVH API
    * https://api.ovh.com/console/#/me/api/application/{applicationId}~GET
* ✅ The corresponding Application has "credentials"
    * https://api.ovh.com/console/#/me/api/credential~GET
* ✅ The related credentials are "validated" and the proper permissions

```json
{
  "allowedIPs": null,
  "applicationId": "*****",
  "creation": "********",
  "credentialId": "*****",
  "expiration": null,
  "lastUse": "2023-06-21T11:55:24+02:00",
  "ovhSupport": false,
  "rules": [
    {
      "method": "GET"
      "path": "/domain/zone/*"
    },
    {
      "method": "PUT",
      "path": "/domain/zone/*"
    },
    {
      "method": "POST",
      "path": "/domain/zone/*"
    },
    {
      "method": "DELETE",
      "path": "/domain/zone/*"
    }
  ],
  "status": "validated"
}
```

I did not find time to go further yet in my troubleshooting.

📝 However, note the `lastUse` time reported. It seems odd to me 😅

**Comment by eze-kiel** [comment]
yep indeed, the `lastUse` field is quite strange :thinking: So probably the program was crashing before even doing the API, which may help us identify the faulty instruction. The PR #10 updates something that is done **after** the API call, so it will probably not fix the issue.

I'll have another look into the code. If in the mean time you have other logs with the caller (also implemented in #10), feel free to post them in this thread :pray:

**Comment by eze-kiel** [comment]
Hi @xakraz , glad to hear you found a probable cause! Keep me posted if the rotation solved your issue

**Comment by xakraz** [comment]
Hi @eze-kiel ,

Unfortunately, I did not have the time to do the credentials rotation 🫤

In the meantime, Cloudflare has released a _DCV_ method (Domain Control Validation) for DNS base certificates.
-> CFCR is not needed anymore 🤷🏻 

I will close this issue.

What do you think about archiving this repo as well since we won't use and maintain it anymore 🙁

**Comment by eze-kiel** [comment]
Hi @xakraz!

Sure, feel free to archive the repository with a note in the README 😉
